export enum GSMButtonStyle {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  DESTRUCTIVE = 'DESTRUCTIVE',
  SOFT_DESTRUCTIVE = 'SOFT_DESTRUCTIVE',
}

export enum GMSButtonSize {
  REGULAR = 'REGULAR',
  SMALL = 'SMALL',
}
